name: 'Discord Commit Notifier'
description: 'Instantly send beautiful commit notifications to Discord when you push to GitHub'
author: 'wilfierd'
branding:
  icon: 'bell'
  color: 'purple'

inputs:
  discord-webhook:
    description: 'Discord webhook URL for sending notifications'
    required: true
  github-token:
    description: 'GitHub token for API access (for fetching user avatars)'
    required: false
    default: ${{ github.token }}
  include-avatar:
    description: 'Include GitHub user avatar in Discord notification'
    required: false
    default: 'true'
  notification-title:
    description: 'Custom title for the notification'
    required: false
    default: '🔔 New Commit Pushed'
  # GitHub context inputs (auto-populated from GitHub context)
  sha:
    description: 'Git commit SHA'
    required: false
    default: ${{ github.sha }}
  commit-message:
    description: 'Commit message'
    required: false
    default: ${{ github.event.head_commit.message }}
  commit-author:
    description: 'Commit author name'
    required: false
    default: ${{ github.event.head_commit.author.name || github.actor }}
  repository:
    description: 'Repository name'
    required: false
    default: ${{ github.repository }}
  commit-url:
    description: 'Commit URL'
    required: false
    default: ${{ github.event.head_commit.url }}
  repo-url:
    description: 'Repository URL'
    required: false
    default: ${{ github.event.repository.html_url }}
  actor:
    description: 'GitHub actor'
    required: false
    default: ${{ github.actor }}
  branch:
    description: 'Branch name'
    required: false
    default: ${{ github.ref_name }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_SHA: ${{ inputs.sha }}
    COMMIT_MESSAGE: ${{ inputs.commit-message }}
    COMMIT_AUTHOR: ${{ inputs.commit-author }}
    GITHUB_REPOSITORY: ${{ inputs.repository }}
    COMMIT_URL: ${{ inputs.commit-url }}
    REPO_URL: ${{ inputs.repo-url }}
    DISCORD_WEBHOOK: ${{ inputs.discord-webhook }}
    GH_TOKEN: ${{ inputs.github-token }}
    INCLUDE_AVATAR: ${{ inputs.include-avatar }}
    NOTIFICATION_TITLE: ${{ inputs.notification-title }}
    GITHUB_ACTOR: ${{ inputs.actor }}
    BRANCH_NAME: ${{ inputs.branch }}
