name: 'Discord Commit Notifier'
description: 'Instantly send beautiful commit notifications to Discord when you push to GitHub'
author: 'wilfierd'
branding:
  icon: 'bell'
  color: 'purple'

inputs:
  discord-webhook:
    description: 'Discord webhook URL for sending notifications'
    required: true
  github-token:
    description: 'GitHub token for API access (for fetching user avatars)'
    required: false
    default: ${{ github.token }}
  include-avatar:
    description: 'Include GitHub user avatar in Discord notification'
    required: false
    default: 'true'
  notification-title:
    description: 'Custom title for the notification'
    required: false
    default: '🔔 New Commit Pushed'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_SHA: ${{ github.sha }}
    COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
    GITHUB_REPOSITORY: ${{ github.repository }}
    COMMIT_URL: ${{ github.event.head_commit.url }}
    REPO_URL: ${{ github.event.repository.html_url }}
    DISCORD_WEBHOOK: ${{ inputs.discord-webhook }}
    GH_TOKEN: ${{ inputs.github-token }}
    INCLUDE_AVATAR: ${{ inputs.include-avatar }}
    NOTIFICATION_TITLE: ${{ inputs.notification-title }}
    GITHUB_ACTOR: ${{ github.actor }}
    BRANCH_NAME: ${{ github.ref_name }}