name: Commit Notifications

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'cache.json'

jobs:
  notify-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Discord notification
        run: |
          # Get short SHA
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          
          # Send to Discord with GitHub-style format
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "embeds": [{
                   "description": "**[${{ github.event.head_commit.author.name }}](${{ github.event.head_commit.author.url }})** committed to **[${{ github.repository }}](${{ github.event.repository.html_url }})**\n\n[`'"$SHORT_SHA"'`](${{ github.event.head_commit.url }}) '"$(echo '${{ github.event.head_commit.message }}' | jq -R .)"'",
                   "color": 7506394,
                   "timestamp": "${{ github.event.head_commit.timestamp }}",
                   "footer": {
                     "text": "${{ github.event.head_commit.author.name }}",
                     "icon_url": "${{ github.event.head_commit.author.avatar_url }}"
                   }
                 }]
               }' \
               ${{ secrets.DISCORD_WEBHOOK }}
        continue-on-error: true
