name: Commit Notifier

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'cache.json'
      - 'README.md'
      - '*.md'
  workflow_dispatch:

jobs:
  commit-notifier:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Setup Go with cache
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
          cache-dependency-path: go.sum
         
      - name: Download dependencies
        run: go mod download

      - name: Run commit notification
        run: |
          go build -o commit-notifier ./cmd/commit-notifier
          ./commit-notifier
        env:
          GITHUB_SHA: ${{ github.sha }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message || 'Manual trigger' }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name || github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          COMMIT_URL: ${{ github.event.head_commit.url || github.event.repository.html_url }}
          REPO_URL: ${{ github.event.repository.html_url }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        continue-on-error: true
