name: Commit Notifications

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'cache.json'

jobs:
  notify-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug commit info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "Author: ${{ github.event.head_commit.author.name }}"
          
      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": "🚀 **New Commit** to `${{ github.repository }}`\n**Message:** ${{ toJson(github.event.head_commit.message) }}\n**Author:** ${{ github.event.head_commit.author.name }}\n**SHA:** `${{ github.sha }}`"
               }' \
               ${{ secrets.DISCORD_WEBHOOK }}
        continue-on-error: true
