name: Commit Notifications

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'cache.json'

jobs:
  notify-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          
      - name: Send commit notification
        run: |
          # Build commit notifier
          go build -o commit-notifier ./cmd/commit-notifier
          
          # Run with environment variables
          ./commit-notifier
        env:
          GITHUB_SHA: ${{ github.sha }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          REPO_URL: ${{ github.event.repository.html_url }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        continue-on-error: true
