name: GitHub Notifier

# on:
#   schedule:
#     # Mỗi 5 phút để check alerts
#     - cron: '*/5 * * * *'
#     # 9h sáng VN = 2h UTC cho daily report
#     - cron: '0 2 * * *'
#   workflow_dispatch:  # Cho phép chạy thủ công
#     inputs:
#       force_daily:
#         description: 'Force daily report'
#         required: false
#         default: false
#         type: boolean
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'cache.json'
      - 'README.md'
      - '*.md'
  workflow_dispatch:  # Chỉ chạy manual
    inputs:
      check_type:
        description: 'Type of check to run'
        required: true
        default: 'instant'
        type: choice
        options:
        - instant
        - daily
        - both

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Download dependencies
        run: go mod download
        
      - name: Build application
        run: go build -o gh-notify main.go
        
      - name: Send commit notification
        if: github.event_name == 'push'
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "embeds": [{
                   "title": "📝 New Commit Pushed",
                   "description": "**Repository:** `${{ github.repository }}`\n**Branch:** `${{ github.ref_name }}`\n**Commit:** `${{ github.sha }}`\n**Message:** ${{ toJson(github.event.head_commit.message) }}\n**Author:** ${{ github.event.head_commit.author.name }}",
                   "color": 3447003,
                   "timestamp": "${{ github.event.head_commit.timestamp }}",
                   "url": "${{ github.event.head_commit.url }}"
                 }]
               }' \
               ${{ secrets.DISCORD_WEBHOOK }}
        continue-on-error: true
               
      - name: Run GitHub Notifier
        run: ./gh-notify
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_USERNAME: ${{ github.actor }}
          CHECK_INTERVAL: '5m'
          DAILY_REPORT_TIME: '02:00'
          CACHE_FILE: 'cache.json'
          TIMEZONE: 'Asia/Ho_Chi_Minh'
          GITHUB_ACTIONS: 'true'
          
      - name: Commit and push cache changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cache.json
          git diff --staged --quiet || git commit -m "Update cache state [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        continue-on-error: true  # Don't fail if no changes to commit
