name: GitHub Notifier

on:
  schedule:
    # 7:00 AM Vietnam = 0:00 UTC - Morning digest
    - cron: '0 0 * * *'
    # 9:00 PM Vietnam = 14:00 UTC - Evening digest  
    - cron: '30 15 * * *'
    # Every 30 minutes for instant checks (reduced from 10 min to reduce cache commits)
    - cron: '*/30 * * * *'
  push:
    branches: [ main ]
    paths-ignore:
      - 'cache.json'
      - 'README.md'
      - '*.md'
  workflow_dispatch:  # Manual trigger
    inputs:
      check_type:
        description: 'Type of check to run'
        required: true
        default: 'instant'
        type: choice
        options:
        - instant
        - daily
        - both

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Cache Go modules
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-v3
          restore-keys: |
            ${{ runner.os }}-go-
        continue-on-error: true  # Don't fail workflow if cache fails

      - name: Clean cache directories on restore failure
        if: failure() || steps.cache.outcome == 'failure'
        run: |
          echo "Cache restore failed, cleaning directories..."
          rm -rf ~/.cache/go-build || true
          rm -rf ~/go/pkg/mod || true
          mkdir -p ~/.cache/go-build
          mkdir -p ~/go/pkg/mod
        continue-on-error: true
            
      - name: Download dependencies
        run: go mod download
        
      - name: Build application
        run: go build -o gh-notify main.go
        
      - name: Run GitHub Notifier
        run: ./gh-notify
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_USERNAME: ${{ github.actor }}
          CHECK_TYPE: ${{ github.event.inputs.check_type || 'both' }}  # Use manual input or default to 'both'
          CHECK_INTERVAL: '5m'
          DAILY_REPORT_TIME: '02:00'
          CACHE_FILE: 'cache.json'
          TIMEZONE: 'Asia/Ho_Chi_Minh'
          GITHUB_ACTIONS: 'true'
          
      - name: Commit and push cache changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cache.json
          git diff --staged --quiet || git commit -m "Update cache state [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        continue-on-error: true  # Don't fail if no changes to commit
