name: GitHub Notifier
on:
  schedule:
    # 7:00 AM Vietnam = 0:00 UTC - Morning digest
    - cron: '0 0 * * *'
    # 9:00 PM Vietnam = 14:00 UTC - Evening digest  
    - cron: '0 14 * * *'
    # Every 1 hour for instant checks
    - cron: '0 * * * *'
  push:
    branches: [ main ]
    paths-ignore:
      - 'cache.json'
      - 'README.md'
      - '*.md'
  workflow_dispatch:
    inputs:
      check_type:
        description: 'Type of check to run'
        required: true
        default: 'instant'
        type: choice
        options:
        - instant
        - morning
        - evening
        - both

jobs:
  notify:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Setup Go with cache
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
          cache-dependency-path: go.sum
         
      - name: Download dependencies
        run: go mod download
       
      - name: Build application
        run: go build -o gh-notify main.go
       
      - name: Run GitHub Notifier
        run: ./gh-notify
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_USERNAME: ${{ github.actor }}
          CHECK_TYPE: ${{ github.event.inputs.check_type || 'auto' }}
          CHECK_INTERVAL: '5m'
          DAILY_REPORT_TIME: '02:00'
          CACHE_FILE: 'cache.json'
          TIMEZONE: 'Asia/Ho_Chi_Minh'
          GITHUB_ACTIONS: 'true'
          SCHEDULE_TYPE: ${{ github.event.schedule }}
         
      - name: Commit and push cache changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cache.json
          git diff --staged --quiet || git commit -m "Update cache state [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        continue-on-error: true